spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/test_task_schema
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always


